data_dir: /home/nadavsc/Desktop/projects/Multi-View-Foams/data
full_groups_dir: /home/nadavsc/Desktop/projects/Multi-View-Foams/data/full_groups
preprocess_dir: /home/nadavsc/Desktop/projects/Multi-View-Foams/data/preprocess
models1_dir: /home/nadavsc/Desktop/projects/Multi-View-Foams/model1/models
models2_dir: /home/nadavsc/Desktop/projects/Multi-View-Foams/model2/models
